In [80]:
import numpy as np

In [81]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [
                  65, 98, 65, 34], [98, 12, 65, 43]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [65, 98, 65, 34],
       [98, 12, 65, 43]])

In [82]:
# bit slicing
matrix[2:4, 2:4]

array([[65, 34],
       [65, 43]])

In [83]:
third_row = matrix[2]
third_row

array([65, 98, 65, 34])

In [84]:
third_row[2]

np.int64(65)

In [ ]:
new2 = [1, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
rimon = np.array(new2)

In [87]:
rimon

array([1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
rimon > 5

array([False, False, False, False,  True,  True,  True,  True])

In [ ]:
new = []

for i in arr:
    if i > 5:
        new.append(i)
new

[6, 7, 8, 9]

In [ ]:
bool_arr = rimon > 5

In [ ]:
rimon = [rimon > 5]

In [93]:
rimon

[array([False, False, False, False,  True,  True,  True,  True])]

In [ ]:
bool_arr = new2

In [96]:
bool_arr

[1, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
rimon = np.arange(20)

In [100]:
rimon

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])