In [ ]:
import numpy as np

In [3]:
np.__version__

'2.2.3'

In [ ]:
arr2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
rimon = np.array(arr2d)

In [6]:
rimon

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.linspace(start=10, stop=20, num=10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
from numpy import random

In [ ]:
np.random.rand(5, 2)

array([[0.85369245, 0.24872598],
       [0.93087728, 0.81075794],
       [0.02807423, 0.91688161],
       [0.97441982, 0.8806072 ],
       [0.37184856, 0.39887263]])

In [ ]:
np.ones([5, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
rimon = np.random.randint(10, 21, size=[6, 3, 4])

In [24]:
rimon.shape

(6, 3, 4)

In [ ]:
rimon.reshape(12, 6)

array([[10, 11, 11, 10, 12, 17],
       [13, 11, 17, 17, 10, 11],
       [10, 14, 17, 19, 19, 19],
       [20, 10, 17, 18, 16, 13],
       [15, 15, 10, 18, 10, 16],
       [11, 12, 14, 12, 15, 18],
       [10, 19, 13, 10, 14, 20],
       [12, 15, 14, 10, 14, 20],
       [19, 14, 19, 12, 11, 12],
       [13, 18, 14, 11, 18, 10],
       [10, 18, 16, 13, 19, 11],
       [20, 17, 11, 10, 13, 16]], dtype=int32)

In [26]:
rimon

array([[[10, 11, 11, 10],
        [12, 17, 13, 11],
        [17, 17, 10, 11]],

       [[10, 14, 17, 19],
        [19, 19, 20, 10],
        [17, 18, 16, 13]],

       [[15, 15, 10, 18],
        [10, 16, 11, 12],
        [14, 12, 15, 18]],

       [[10, 19, 13, 10],
        [14, 20, 12, 15],
        [14, 10, 14, 20]],

       [[19, 14, 19, 12],
        [11, 12, 13, 18],
        [14, 11, 18, 10]],

       [[10, 18, 16, 13],
        [19, 11, 20, 17],
        [11, 10, 13, 16]]], dtype=int32)